services:

  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    ports:
      - 8082:5001
    environment:
      APPKEY: k12Ucv953gcITag006o8d6xD3TI5Q2XT
    restart: always
    depends_on:
      - api

  api:
    container_name: api
    build:
      context: api
      dockerfile: Dockerfile.dev
    ports:
      - 8081:5000
    environment:
      MONGOUN: root
      MONGOPW: example
    depends_on:
      - mongo

  mongo:
    container_name: mongo-db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
        - 27117:27017
    volumes:
      - /datadir:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8090:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
        - mongo