services:

  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    environment:
      APPKEY: ${FRONTENDAPPKEY}
    ports:
      - 8082:5001
    restart: always
    depends_on:
      - api

  api:
    container_name: api
    build:
      context: api
      dockerfile: Dockerfile.dev
    environment:
      MONGOUN: ${MONGOUN}
      MONGOPW: ${MONGOPW}
      APPKEY: ${APIAPPKEY}
    ports:
      - 8081:5000
    depends_on:
      - mongo

  mongo:
    container_name: mongo-db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGOUN}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGOPW}
    ports:
        - 27117:27017
    volumes:
      - /datadir:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8090:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGOUN}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGOPW}
      ME_CONFIG_MONGODB_URL: ${MONGOURL}
      ME_CONFIG_BASICAUTH: false
    depends_on:
        - mongo