FROM python:alpine as builder

WORKDIR /app

COPY requirements.txt /app
RUN pip install --no-cache-dir --upgrade -r requirements.txt
RUN adduser --system --no-create-home nonroot

COPY . /app

EXPOSE 8000
USER nonroot

CMD ["gunicorn", "--bind", "0.0.0.0:5000", "--workers=4", "api:app"]