name: Docker Build

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image using Compose
      run: |
        git pull origin main
        sudo docker compose down
        sudo docker compose up -d --build
      working-directory: /home/matheusdu/personal-site-v2
