name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image using Compose
      run: |
        sudo docker compose down
        sudo docker compose up -d --build
