name: Docker Image CI

on: self-hosted
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        cd api
        docker build . --file Dockerfile.prod --tag personal-site-prod:$(date +%s)
